export const COUNTRIES = [
  "Belgique",
  "France",
  "Pays-Bas",
  "Allemagne",
  "Luxembourg",
  "Algérie",
  "Autriche",
  "Bulgarie",
  "Canada",
  "Chypre",
  "Côte d'Ivoire",
  "Croatie",
  "Cuba",
  "Danemark",
  "Espagne",
  "Estonie",
  "États-Unis",
  "Finlande",
  "Grèce",
  "Hongrie",
  "Irlande",
  "Islande",
  "Italie",
  "Lettonie",
  "Lituanie",
  "Malte",
  "Maroc",
  "Mexique",
  "Norvège",
  "Pologne",
  "Portugal",
  "République tchèque",
  "Roumanie",
  "Royaume-Uni",
  "Sénégal",
  "Slovaquie",
  "Slovénie",
  "Suède",
  "Suisse",
  "Tunisie",
  "Vénézuéla",
  "Autre",
];

export const PAYMENT_METHODS = ["Espèces", "Carte bancaire", "Sans contact", "Bancontact", "Payconiq", "Virement", "Chèque"];

export const VENUE_TYPES = ["Bar", "Café", "Restaurant", "Pub", "Brasserie", "Cave à bières", "Épicerie", "Autre"];
