export const COUNTRIES = [
  "Belgique",
  "France",
  "Pays-Bas",
  "Allemagne",
  "Luxembourg",
  "Algérie",
  "Autriche",
  "Bulgarie",
  "Canada",
  "Chypre",
  "Côte d'Ivoire",
  "Croatie",
  "Cuba",
  "Danemark",
  "Espagne",
  "Estonie",
  "États-Unis",
  "Finlande",
  "Grèce",
  "Hongrie",
  "Irlande",
  "Islande",
  "Italie",
  "Lettonie",
  "Lituanie",
  "Malte",
  "Maroc",
  "Mexique",
  "Norvège",
  "Pologne",
  "Portugal",
  "République tchèque",
  "Roumanie",
  "Royaume-Uni",
  "Sénégal",
  "Slovaquie",
  "Slovénie",
  "Suède",
  "Suisse",
  "Tunisie",
  "Vénézuéla",
  "Autre",
];

export const PAYMENT_METHODS = ["Espèces", "Carte bancaire", "Sans contact", "Bancontact", "Payconiq", "Virement", "Chèque"];

export const VENUE_TYPES = [
  "Bar",
  "Café",
  "Taverne",
  "Bistrot",
  "Pub",
  "Estaminet",
  "Café de quartier",
  "Brasserie",
  "Restaurant",
  "Brasserie-Restaurant",
  "Irish Pub",
  "Cafétaria",
  "Buvette",
  "Bar d'hôtel",
  "Microbrasserie",
  "Salle de spectacle",
  "Salle de concert",
  "Salle de location",
  "Bar lounge",
  "Bar-concert",
  "Piano bar",
  "Karaoké bar",
  "Bar dansant",
  "Discothèque",
  "Cabaret",
  "Club privé",
  "Bar e-sport",
  "Bar à jeux électroniques",
  "Bar à jeux d'arcade",
  "Bar à jeux de société",
  "Bowling",
  "Terrasse",
  "Grande terrasse",
  "Rooftop",
  "Bar à bières",
  "Bar à vins",
  "Bar à champagne",
  "Bar à cocktails",
  "Bar à rhum",
  "Bar à whiskey",
  "Bar à gin",
  "Bar à shot",
];

export const PHONE_PREFIXES = {
  "Belgique": "+32",
  "France": "+33",
  "Pays-Bas": "+31",
  "Allemagne": "+49",
  "Luxembourg": "+352",
  "Algérie": "+213",
  "Autriche": "+43",
  "Bulgarie": "+359",
  "Canada": "+1",
  "Chypre": "+357",
  "Côte d'Ivoire": "+225",
  "Croatie": "+385",
  "Cuba": "+53",
  "Danemark": "+45",
  "Espagne": "+34",
  "Estonie": "+372",
  "États-Unis": "+1",
  "Finlande": "+358",
  "Grèce": "+30",
  "Hongrie": "+36",
  "Irlande": "+353",
  "Islande": "+354",
  "Italie": "+39",
  "Lettonie": "+371",
  "Lituanie": "+370",
  "Malte": "+356",
  "Maroc": "+212",
  "Mexique": "+52",
  "Norvège": "+47",
  "Pologne": "+48",
  "Portugal": "+351",
  "République tchèque": "+420",
  "Roumanie": "+40",
  "Royaume-Uni": "+44",
  "Sénégal": "+221",
  "Slovaquie": "+421",
  "Slovénie": "+386",
  "Suède": "+46",
  "Suisse": "+41",
  "Tunisie": "+216",
  "Vénézuéla": "+58",
  "Autre": "",
};

export const PRODUCER_TYPES = [
  "Brasserie",
  "Micro-brasserie",
  "Distillerie",
  "Cidrerie",
  "Domaine viticole",
  "Hydromellerie",
  "Torréfacteur",
  "Boissons sans alcool",
  "Alimentaire",
];

export const PRODUCER_PROFILES = [
  "Micro-producteur",
  "Artisanal",
  "Local",
  "Indépendant",
  "Industriel",
  "Groupe",
  "Multinationale",
  "Coopérative",
];
