// Palette reprise de l'app principale — n'était pas encore exportée ici, alors que
// icons.jsx s'y référait déjà (jamais déclenché tant que ce fichier n'était pas utilisé).
export const COLORS = {
  paper: "#0D1B2A",
  paperAlt: "#28405C",
  surface: "#16273D",
  ink: "#F2F2E8",
  inkSoft: "#8792A6",
  amber: "#39FF66",
  amberDark: "#2BD955",
};

export const COUNTRIES = [
  { code: "belgique", fr: "Belgique" },
  { code: "france", fr: "France" },
  { code: "pays_bas", fr: "Pays-Bas" },
  { code: "allemagne", fr: "Allemagne" },
  { code: "luxembourg", fr: "Luxembourg" },
  { code: "algerie", fr: "Algérie" },
  { code: "autriche", fr: "Autriche" },
  { code: "bulgarie", fr: "Bulgarie" },
  { code: "canada", fr: "Canada" },
  { code: "chypre", fr: "Chypre" },
  { code: "cote_d_ivoire", fr: "Côte d'Ivoire" },
  { code: "croatie", fr: "Croatie" },
  { code: "cuba", fr: "Cuba" },
  { code: "danemark", fr: "Danemark" },
  { code: "espagne", fr: "Espagne" },
  { code: "estonie", fr: "Estonie" },
  { code: "etats_unis", fr: "États-Unis" },
  { code: "finlande", fr: "Finlande" },
  { code: "grece", fr: "Grèce" },
  { code: "hongrie", fr: "Hongrie" },
  { code: "irlande", fr: "Irlande" },
  { code: "islande", fr: "Islande" },
  { code: "italie", fr: "Italie" },
  { code: "lettonie", fr: "Lettonie" },
  { code: "lituanie", fr: "Lituanie" },
  { code: "malte", fr: "Malte" },
  { code: "maroc", fr: "Maroc" },
  { code: "mexique", fr: "Mexique" },
  { code: "norvege", fr: "Norvège" },
  { code: "pologne", fr: "Pologne" },
  { code: "portugal", fr: "Portugal" },
  { code: "republique_tcheque", fr: "République tchèque" },
  { code: "roumanie", fr: "Roumanie" },
  { code: "royaume_uni", fr: "Royaume-Uni" },
  { code: "senegal", fr: "Sénégal" },
  { code: "slovaquie", fr: "Slovaquie" },
  { code: "slovenie", fr: "Slovénie" },
  { code: "suede", fr: "Suède" },
  { code: "suisse", fr: "Suisse" },
  { code: "tunisie", fr: "Tunisie" },
  { code: "venezuela", fr: "Vénézuéla" },
  { code: "international", fr: "International" },
  { code: "autre", fr: "Autre" },
];

export const PAYMENT_METHODS = [
  { code: "especes", fr: "Espèces" },
  { code: "carte_bancaire", fr: "Carte bancaire" },
  { code: "visa", fr: "Visa" },
  { code: "mastercard", fr: "Mastercard" },
  { code: "maestro_debit", fr: "Maestro/Debit" },
  { code: "sans_contact", fr: "Sans contact" },
  { code: "apple_pay", fr: "Apple Pay" },
  { code: "google_pay", fr: "Google Pay" },
  { code: "samsung_wallet", fr: "Samsung Wallet" },
  { code: "paiement_mobile_qr", fr: "Paiement mobile/QR" },
  { code: "payconiq", fr: "Payconiq" },
  { code: "paiement_en_ligne", fr: "Paiement en ligne" },
  { code: "cheques_repas", fr: "Chèques-repas" },
  { code: "facturation", fr: "Facturation" },
  { code: "prepaye", fr: "Prépayé" },
  { code: "carte_rechargeable", fr: "Carte rechargeable" },
  { code: "bracelet_rfid", fr: "Bracelet RFID" },
  { code: "jetons", fr: "Jetons" },
  { code: "bon_cadeau", fr: "Bon cadeau" },
];

// Système d'appréciation des lieux (5 paliers positifs, échelle d'enthousiasme croissant —
// jamais "mauvais → bon"). Mêmes clés que côté app publique.
export const RATING_LABELS = [
  { code: "NICE", fr: "Sympa", value: 1 },
  { code: "VERY_GOOD", fr: "Très bien", value: 2 },
  { code: "EXCELLENT", fr: "Excellent", value: 3 },
  { code: "EXCEPTIONAL", fr: "Exceptionnel", value: 4 },
  { code: "MUST_VISIT", fr: "Incontournable", value: 5 },
];

export const VENUE_TYPES = [
  { code: "bar", fr: "Bar" },
  { code: "cafe", fr: "Café" },
  { code: "taverne", fr: "Taverne" },
  { code: "bistrot", fr: "Bistrot" },
  { code: "pub", fr: "Pub" },
  { code: "estaminet", fr: "Estaminet" },
  { code: "cafe_de_quartier", fr: "Café de quartier" },
  { code: "brasserie", fr: "Brasserie" },
  { code: "restaurant", fr: "Restaurant" },
  { code: "brasserie_restaurant", fr: "Brasserie-Restaurant" },
  { code: "irish_pub", fr: "Irish Pub" },
  { code: "cafetaria", fr: "Cafétaria" },
  { code: "buvette", fr: "Buvette" },
  { code: "bar_d_hotel", fr: "Bar d'hôtel" },
  { code: "microbrasserie", fr: "Microbrasserie" },
  { code: "salle_de_spectacle", fr: "Salle de spectacle" },
  { code: "salle_de_concert", fr: "Salle de concert" },
  { code: "salle_de_location", fr: "Salle de location" },
  { code: "bar_lounge", fr: "Bar lounge" },
  { code: "bar_concert", fr: "Bar-concert" },
  { code: "piano_bar", fr: "Piano bar" },
  { code: "karaoke_bar", fr: "Karaoké bar" },
  { code: "bar_dansant", fr: "Bar dansant" },
  { code: "discotheque", fr: "Discothèque" },
  { code: "cabaret", fr: "Cabaret" },
  { code: "club_prive", fr: "Club privé" },
  { code: "bar_e_sport", fr: "Bar e-sport" },
  { code: "bar_a_jeux_electroniques", fr: "Bar à jeux électroniques" },
  { code: "bar_a_jeux_d_arcade", fr: "Bar à jeux d'arcade" },
  { code: "bar_a_jeux_de_societe", fr: "Bar à jeux de société" },
  { code: "bowling", fr: "Bowling" },
  { code: "terrasse", fr: "Terrasse" },
  { code: "grande_terrasse", fr: "Grande terrasse" },
  { code: "rooftop", fr: "Rooftop" },
  { code: "bar_a_bieres", fr: "Bar à bières" },
  { code: "bar_a_vins", fr: "Bar à vins" },
  { code: "bar_a_champagne", fr: "Bar à champagne" },
  { code: "bar_a_cocktails", fr: "Bar à cocktails" },
  { code: "bar_a_rhum", fr: "Bar à rhum" },
  { code: "bar_a_whiskey", fr: "Bar à whiskey" },
  { code: "bar_a_gin", fr: "Bar à gin" },
  { code: "bar_a_shot", fr: "Bar à shot" },
  { code: "drink_food_shop", fr: "Drink & Food Shop" },
  { code: "karaokes_occasionnels", fr: "Karaokés occasionnels" },
  { code: "concerts_occasionnels", fr: "Concerts occasionnels" },
  { code: "billard", fr: "Billard" },
  { code: "babyfoot_kicker", fr: "Babyfoot - Kicker" },
  { code: "jeu_de_flechettes", fr: "Jeu de fléchettes" },
  { code: "bingo", fr: "Bingo" },
];

export const PHONE_PREFIXES = {
  belgique: "+32",
  france: "+33",
  pays_bas: "+31",
  allemagne: "+49",
  luxembourg: "+352",
  algerie: "+213",
  autriche: "+43",
  bulgarie: "+359",
  canada: "+1",
  chypre: "+357",
  cote_d_ivoire: "+225",
  croatie: "+385",
  cuba: "+53",
  danemark: "+45",
  espagne: "+34",
  estonie: "+372",
  etats_unis: "+1",
  finlande: "+358",
  grece: "+30",
  hongrie: "+36",
  irlande: "+353",
  islande: "+354",
  italie: "+39",
  lettonie: "+371",
  lituanie: "+370",
  malte: "+356",
  maroc: "+212",
  mexique: "+52",
  norvege: "+47",
  pologne: "+48",
  portugal: "+351",
  republique_tcheque: "+420",
  roumanie: "+40",
  royaume_uni: "+44",
  senegal: "+221",
  slovaquie: "+421",
  slovenie: "+386",
  suede: "+46",
  suisse: "+41",
  tunisie: "+216",
  venezuela: "+58",
  autre: ""
};

export const PRODUCER_TYPES = [
  { code: "brasserie", fr: "Brasserie" },
  { code: "micro_brasserie", fr: "Micro-brasserie" },
  { code: "distillerie", fr: "Distillerie" },
  { code: "cidrerie", fr: "Cidrerie" },
  { code: "domaine_viticole", fr: "Domaine viticole" },
  { code: "hydromellerie", fr: "Hydromellerie" },
  { code: "torrefacteur", fr: "Torréfacteur" },
  { code: "boissons_sans_alcool", fr: "Boissons sans alcool" },
  { code: "alimentaire", fr: "Alimentaire" },
];

export const PRODUCER_PROFILES = [
  { code: "micro_producteur", fr: "Micro-producteur" },
  { code: "artisanal", fr: "Artisanal" },
  { code: "local", fr: "Local" },
  { code: "independant", fr: "Indépendant" },
  { code: "industriel", fr: "Industriel" },
  { code: "groupe", fr: "Groupe" },
  { code: "multinationale", fr: "Multinationale" },
  { code: "cooperative", fr: "Coopérative" },
];

export const BRAND_CLASSIFICATIONS = [
  { code: "biere", fr: "Bière" },
  { code: "vin", fr: "Vin" },
  { code: "bulles", fr: "Bulles (champagne, crémant...)" },
  { code: "spiritueux", fr: "Spiritueux" },
  { code: "cidre", fr: "Cidre" },
  { code: "soft_soda", fr: "Soft / Soda" },
  { code: "eau", fr: "Eau" },
  { code: "boisson_energetique", fr: "Boisson énergétique" },
  { code: "cafe", fr: "Café" },
  { code: "the", fr: "Thé" },
  { code: "snacks", fr: "Snacks" },
  { code: "autre", fr: "Autre" },
];

export const BRAND_TYPES = [
  { code: "artisanale", fr: "Artisanale" },
  { code: "locale", fr: "Locale" },
  { code: "regionale", fr: "Régionale" },
  { code: "nationale", fr: "Nationale" },
  { code: "internationale", fr: "Internationale" },
];

// Correspondance entre nos codes pays internes (COUNTRIES) et les codes ISO 3166-1 alpha-2
// attendus par Geoapify pour restreindre l'autocomplétion d'adresse au bon pays.
export const COUNTRY_ISO_CODES = {
  belgique: "be",
  france: "fr",
  pays_bas: "nl",
  allemagne: "de",
  luxembourg: "lu",
  algerie: "dz",
  autriche: "at",
  bulgarie: "bg",
  canada: "ca",
  chypre: "cy",
  cote_d_ivoire: "ci",
  croatie: "hr",
  cuba: "cu",
  danemark: "dk",
  espagne: "es",
  estonie: "ee",
  etats_unis: "us",
  finlande: "fi",
  grece: "gr",
  hongrie: "hu",
  irlande: "ie",
  islande: "is",
  italie: "it",
  lettonie: "lv",
  lituanie: "lt",
  malte: "mt",
  maroc: "ma",
  mexique: "mx",
  norvege: "no",
  pologne: "pl",
  portugal: "pt",
  republique_tcheque: "cz",
  roumanie: "ro",
  royaume_uni: "gb",
  senegal: "sn",
  slovaquie: "sk",
  slovenie: "si",
  suede: "se",
  suisse: "ch",
  tunisie: "tn",
  venezuela: "ve",
};

export const CITIES_BY_COUNTRY = {
  Belgique: [
    "Waimes",
    "Malmedy",
    "Bütgenbach",
    "Stavelot",
    "Robertville",
    "Ovifat",
    "Weismes",
    "Sourbrodt",
    "Faymonville",
    "Ligneuville",
    "Longfaye",
    "Eupen",
    "Saint-Vith",
    "Spa",
    "Verviers",
    "Trois-Ponts",
    "Vielsalm",
    "Bastogne",
    "Liège",
    "Huy",
    "Waremme",
    "Seraing",
    "Herstal",
    "Namur",
    "Dinant",
    "Ciney",
    "Rochefort",
    "Marche-en-Famenne",
    "La Roche-en-Ardenne",
    "Durbuy",
    "Charleroi",
    "Mons",
    "Tournai",
    "La Louvière",
    "Mouscron",
    "Ath",
    "Nivelles",
    "Wavre",
    "Ottignies-Louvain-la-Neuve",
    "Braine-l'Alleud",
    "Bruxelles",
    "Ixelles",
    "Schaerbeek",
    "Uccle",
    "Anderlecht",
    "Etterbeek",
    "Woluwe-Saint-Lambert",
    "Anvers",
    "Gand",
    "Bruges",
    "Louvain",
    "Malines",
    "Ostende",
    "Courtrai",
    "Hasselt",
    "Genk",
    "Roulers",
    "Turnhout",
    "Alost",
    "Saint-Nicolas",
  ],
  France: [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Saint-Étienne",
    "Toulon",
    "Le Havre",
    "Grenoble",
    "Dijon",
    "Angers",
    "Nîmes",
    "Villeurbanne",
    "Clermont-Ferrand",
    "Le Mans",
    "Aix-en-Provence",
    "Brest",
    "Tours",
    "Amiens",
    "Limoges",
    "Annecy",
    "Metz",
    "Besançon",
    "Perpignan",
    "Orléans",
    "Rouen",
    "Mulhouse",
    "Caen",
    "Nancy",
    "Avignon",
    "Sedan",
    "Charleville-Mézières",
    "Givet",
  ],
  Luxembourg: [
    "Luxembourg",
    "Esch-sur-Alzette",
    "Differdange",
    "Dudelange",
    "Ettelbruck",
    "Diekirch",
    "Wiltz",
    "Echternach",
    "Rumelange",
    "Grevenmacher",
    "Remich",
    "Vianden",
    "Clervaux",
  ],
  Allemagne: [
    "Berlin",
    "Hambourg",
    "Munich",
    "Cologne",
    "Francfort",
    "Stuttgart",
    "Düsseldorf",
    "Leipzig",
    "Dortmund",
    "Essen",
    "Brême",
    "Dresde",
    "Hanovre",
    "Nuremberg",
    "Aix-la-Chapelle",
    "Trèves",
    "Sarrebruck",
    "Bonn",
    "Mannheim",
    "Wiesbaden",
  ],
  "Pays-Bas": [
    "Amsterdam",
    "Rotterdam",
    "La Haye",
    "Utrecht",
    "Eindhoven",
    "Groningue",
    "Tilburg",
    "Almere",
    "Breda",
    "Nimègue",
    "Maastricht",
    "Arnhem",
    "Haarlem",
    "Enschede",
    "Amersfoort",
    "Leyde",
    "Zwolle",
    "Venlo",
    "Roosendaal",
  ],
  Algérie: ["Alger", "Oran", "Constantine", "Annaba", "Blida", "Batna", "Sétif", "Sidi Bel Abbès", "Tlemcen"],
  Autriche: ["Vienne", "Graz", "Linz", "Salzbourg", "Innsbruck", "Klagenfurt", "Villach", "Wels"],
  Bulgarie: ["Sofia", "Plovdiv", "Varna", "Burgas", "Roussé"],
  Canada: ["Toronto", "Montréal", "Vancouver", "Ottawa", "Calgary", "Edmonton", "Québec", "Winnipeg"],
  Chypre: ["Nicosie", "Limassol", "Larnaca", "Paphos", "Famagouste"],
  "Côte d'Ivoire": ["Abidjan", "Bouaké", "Yamoussoukro", "San-Pédro", "Korhogo"],
  Croatie: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Dubrovnik"],
  Danemark: ["Copenhague", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  Espagne: ["Madrid", "Barcelone", "Valence", "Séville", "Saragosse", "Malaga", "Murcie", "Bilbao", "Alicante", "Palma"],
  Estonie: ["Tallinn", "Tartu", "Narva", "Pärnu"],
  "États-Unis": ["New York", "Los Angeles", "Chicago", "Houston", "Miami", "San Francisco", "Boston", "Washington", "Seattle", "Las Vegas"],
  Finlande: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Turku", "Oulu"],
  Grèce: ["Athènes", "Thessalonique", "Patras", "Héraklion", "Larissa"],
  Hongrie: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs"],
  Irlande: ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  Islande: ["Reykjavik", "Kópavogur", "Akureyri"],
  Italie: ["Rome", "Milan", "Naples", "Turin", "Palerme", "Gênes", "Bologne", "Florence", "Venise", "Vérone"],
  Lettonie: ["Riga", "Daugavpils", "Liepāja"],
  Lituanie: ["Vilnius", "Kaunas", "Klaipėda"],
  Malte: ["La Valette", "Birkirkara", "Mosta", "Sliema"],
  Maroc: ["Casablanca", "Rabat", "Fès", "Marrakech", "Tanger", "Agadir", "Meknès", "Oujda"],
  Norvège: ["Oslo", "Bergen", "Trondheim", "Stavanger"],
  Pologne: ["Varsovie", "Cracovie", "Łódź", "Wrocław", "Poznań", "Gdańsk"],
  Portugal: ["Lisbonne", "Porto", "Braga", "Coimbra", "Faro"],
  "République tchèque": ["Prague", "Brno", "Ostrava", "Plzeň"],
  Roumanie: ["Bucarest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța"],
  "Royaume-Uni": ["Londres", "Manchester", "Birmingham", "Glasgow", "Édimbourg", "Liverpool", "Leeds", "Bristol"],
  Sénégal: ["Dakar", "Thiès", "Rufisque", "Kaolack", "Saint-Louis"],
  Slovaquie: ["Bratislava", "Košice", "Prešov"],
  Slovénie: ["Ljubljana", "Maribor", "Celje"],
  Suède: ["Stockholm", "Göteborg", "Malmö", "Uppsala"],
  Suisse: ["Genève", "Zurich", "Berne", "Bâle", "Lausanne", "Lucerne", "Lugano", "Fribourg"],
  Tunisie: ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte"],
};

// Constantes liées aux produits/menus — reprises de bibamus-web pour rester cohérentes avec
// l'app publique. Étaient importées par utils.js mais jamais exportées ici (jamais déclenché
// tant qu'aucun écran de cette plateforme n'utilisait la gestion de carte).
export const MENU_CATEGORIES = ["Bières & Cidres", "Vins & Bulles", "Spiritueux", "Shots", "Cocktails / Mocktails", "Softs & Eaux", "Boissons chaudes", "Snacks"];

export const DRINK_TYPES = ["Bières & Cidres", "Vins & Bulles", "Spiritueux", "Cocktails / Mocktails", "Softs & Eaux", "Boissons chaudes", "Snacks", "Génériques"];

export const DRINK_TYPE_MIGRATIONS = {
  "Bière pils": "Bières & Cidres",
  "Bière spéciales": "Bières & Cidres",
  Bière: "Bières & Cidres",
  Bières: "Bières & Cidres",
  "Vin & bulles": "Vins & Bulles",
  "Vins & bulles": "Vins & Bulles",
  Alcools: "Spiritueux",
  Cocktails: "Cocktails / Mocktails",
  Shooters: "Spiritueux",
  Shots: "Spiritueux",
  Eau: "Softs & Eaux",
  Soft: "Softs & Eaux",
  "Softs & eaux": "Softs & Eaux",
  "Boisson chaude": "Boissons chaudes",
  Snack: "Snacks",
};

export const NON_ALCOHOLIC_DRINK_TYPES = ["Softs & Eaux", "Boissons chaudes", "Snacks"];

export const SERVING_MODE_LABELS = { bouteille: "Bouteille", canette: "Canette", verre: "Au verre", fut: "On tap" };

export const MONTH_NAMES_FR = ["janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"];

export const DRINK_FIELD_LABELS = {
  name: "Nom complet du produit",
  type: "Type",
  kcalPer100ml: "Calories (pour 100ml)",
  beerTags: "Style & caractéristiques",
  abv: "Degré d'alcool",
  brand: "Marque du produit",
  brewery: "Producteur",
  nationality: "Pays d'origine de la marque",
  glutenFree: "Sans gluten",
  bio: "Label Bio",
  volumeCl: "Volume par défaut",
  servingMode: "Type de service par défaut",
  snackType: "Type de produit",
  weightG: "Poids par défaut",
  isGeneric: "Produit générique",
  averagePrice: "Prix indicatif",
  countsAsDrinkId: "Compte comme",
  description: "Description",
};

// Constantes supplémentaires liées aux produits — mêmes découvertes tardives (imports jamais
// déclenchés jusqu'ici) que le bloc ci-dessus.
export const COUNTRY_FLAGS = {
  Belgique: "🇧🇪",
  France: "🇫🇷",
  Luxembourg: "🇱🇺",
  Allemagne: "🇩🇪",
  "Pays-Bas": "🇳🇱",
  Algérie: "🇩🇿",
  Angleterre: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  Autriche: "🇦🇹",
  Bermudes: "🇧🇲",
  Bulgarie: "🇧🇬",
  Canada: "🇨🇦",
  Chypre: "🇨🇾",
  "Côte d'Ivoire": "🇨🇮",
  Croatie: "🇭🇷",
  Cuba: "🇨🇺",
  Danemark: "🇩🇰",
  Écosse: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Espagne: "🇪🇸",
  Estonie: "🇪🇪",
  "États-Unis": "🇺🇸",
  Finlande: "🇫🇮",
  Grèce: "🇬🇷",
  Hongrie: "🇭🇺",
  Irlande: "🇮🇪",
  Islande: "🇮🇸",
  Italie: "🇮🇹",
  Japon: "🇯🇵",
  Lettonie: "🇱🇻",
  Lituanie: "🇱🇹",
  Malte: "🇲🇹",
  Maroc: "🇲🇦",
  Mexique: "🇲🇽",
  Norvège: "🇳🇴",
  Pologne: "🇵🇱",
  Portugal: "🇵🇹",
  "République tchèque": "🇨🇿",
  Roumanie: "🇷🇴",
  "Royaume-Uni": "🇬🇧",
  Sénégal: "🇸🇳",
  Slovaquie: "🇸🇰",
  Slovénie: "🇸🇮",
  Suède: "🇸🇪",
  Suisse: "🇨🇭",
  Tunisie: "🇹🇳",
  Vénézuéla: "🇻🇪",
};

export const GLUTEN_BIO_ELIGIBLE_TYPES = ["Bières & Cidres"];
export const NATIONALITY_ELIGIBLE_TYPES = ["Bières & Cidres", "Vins & Bulles", "Spiritueux", "Softs & Eaux", "Boissons chaudes"];
export const DRINK_VOLUMES_CL = [2, 2.5, 3, 3.5, 4, 4.5, 5, 6, 7, 8, 9, 10, 12, 12.5, 15, 17, 18, 20, 22, 25, 28, 30, 33, 35, 40, 50, 66, 70, 75, 100, 120, 150, 200, 300];
export const SNACK_WEIGHTS_G = [25, 40, 45, 50, 75, 100, 125, 150, 200, 250, 300, 400, 500];
export const BEER_TYPES = ["Bières & Cidres"];
export const VOLUME_DISPLAY_TYPES = ["Bières & Cidres", "Softs & Eaux"];

export const BEER_STYLE_TAGS = [
  "Blonde",
  "Blonde dorée",
  "Ambrée",
  "Rousse",
  "Brune",
  "Noire",
  "Blanche",
  "Rouge",
  "Rubis",
  "Pils",
  "Fruitée",
  "Lager blonde",
  "Export",
  "Session Lager",
  "Pale Lager",
  "Bière de table",
  "Sans alcool",
  "Faible en alcool",
  "Bière légère",
  "Low calories",
  "Blonde belge",
  "Bière forte",
  "Blonde forte",
  "Brune forte",
  "Fruitée forte",
  "Spéciale belge",
  "Bière d'Abbaye",
  "Bière Trappiste",
  "Double",
  "Triple",
  "Quadrupel",
  "Belgian Strong Ale",
  "Dark Strong Ale",
  "Saison",
  "Bière de garde",
  "Bière brut",
  "Bière de Noël",
  "Bière estivale",
  "Bière d'Hiver",
  "Bière de récolte",
  "Weissbier",
  "Gose",
  "Amber Ale",
  "Porter",
  "Stout",
  "Irish Dry Stout",
  "Chocolate Stout",
  "Black IPA",
  "Pale Ale",
  "Hoppy Pale Ale",
  "IPA",
  "New England IPA",
  "Hazy IPA",
  "Sour IPA",
  "Pilsner",
  "Lambic",
  "Gueuze",
  "Kriek",
  "Cerise",
  "Framboise",
  "Pêche",
  "Faro",
  "Biologique",
  "Sans gluten",
  "Premium",
];

export const SOFT_DRINK_TAGS = [
  "Soda",
  "Cola",
  "Limonade",
  "Orangeade",
  "Tonic",
  "Thé glacé",
  "Jus de fruits",
  "Boissons énergisantes",
  "Light",
  "Zero",
  "Pétillant",
  "Fortement pétillant",
  "Non-pétillant",
  "Ginger Ale",
  "Ginger Beer",
  "Sirop",
  "Aromatisé",
  "Bio",
  "Caféiné",
  "Sans caféine",
  "Végane",
];

export const SPIRIT_TAGS = ["Vodka", "Whisky", "Gin", "Rhum", "Tequila"];
export const WINE_TAGS = ["Sec", "Demi-sec", "Doux"];
